# Generated by Django 5.2.5 on 2026-02-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='SO number (e.g., 1, 2, 3)')),
                ('title', models.CharField(help_text='Short title for the SO', max_length=255)),
                ('description', models.TextField(help_text='Full description of the student outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Outcome',
                'verbose_name_plural': 'Student Outcomes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='PI number within the SO (e.g., 1, 2, 3)')),
                ('description', models.TextField(help_text='Description of what this indicator measures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_indicators', to='so.studentoutcome')),
            ],
            options={
                'verbose_name': 'Performance Indicator',
                'verbose_name_plural': 'Performance Indicators',
                'ordering': ['student_outcome', 'number'],
                'unique_together': {('student_outcome', 'number')},
            },
        ),
    ]
