# Generated by Django 5.2.9 on 2026-02-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performanceindicator',
            options={'ordering': ['student_outcome', 'number']},
        ),
        migrations.AlterModelOptions(
            name='studentoutcome',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PerformanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='so.performanceindicator')),
            ],
            options={
                'ordering': ['performance_indicator', 'order'],
                'unique_together': {('performance_indicator', 'order')},
            },
        ),
    ]
