# Generated by Django 5.2.5 on 2026-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classess', '0003_faculty_section_assigned_faculty_and_more'),
        ('courses', '0005_coursesomapping_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='school_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'course', 'school_year')},
        ),
    ]
