# Generated by Django 5.2.9 on 2026-02-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classess', '0003_faculty_section_assigned_faculty_and_more'),
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='classess.section')),
                ('student_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='so.studentoutcome')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('section', 'student_outcome', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.assessment')),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.performanceindicator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_grades', to='classess.student')),
            ],
            options={
                'unique_together': {('assessment', 'student', 'performance_indicator')},
            },
        ),
    ]
