# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        ("so", "0002_alter_performanceindicator_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="grade",
            name="criterion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="so.performancecriterion",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="performance_indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="so.performanceindicator",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("criterion__isnull", False)),
                fields=("assessment", "student", "criterion"),
                name="unique_grade_per_criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("performance_indicator__isnull", False)),
                fields=("assessment", "student", "performance_indicator"),
                name="unique_grade_per_indicator",
            ),
        ),
    ]
