# Generated by Django 5.2.5 on 2026-02-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=20)),
                ('name', models.CharField(help_text='Course name', max_length=255)),
                ('section', models.CharField(blank=True, default='', help_text='Section (e.g., A, B)', max_length=10)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Course description')),
                ('credits', models.PositiveIntegerField(default=3, help_text='Number of credits')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=20)),
                ('instructor', models.CharField(blank=True, default='', help_text='Instructor name', max_length=255)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Number of enrolled students')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_sos', models.ManyToManyField(blank=True, help_text='Student Outcomes mapped to this course', related_name='courses', to='so.studentoutcome')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
                'unique_together': {('code', 'section', 'academic_year')},
            },
        ),
    ]
