# Generated by Django 5.2.9 on 2026-02-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_curriculum_alter_course_unique_together_and_more'),
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mapped_sos',
        ),
        migrations.CreateModel(
            name='CourseSOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('year_level', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('credits', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_mappings', to='courses.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum')),
                ('mapped_sos', models.ManyToManyField(blank=True, related_name='course_mappings', to='so.studentoutcome')),
            ],
            options={
                'verbose_name': 'Course SO Mapping',
                'verbose_name_plural': 'Course SO Mappings',
                'ordering': ['code'],
            },
        ),
    ]
