# Generated by Django 5.2.9 on 2026-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_mapped_sos_coursesomapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesomapping',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='2023-2024', help_text='Academic year for this mapping', max_length=9),
        ),
    ]
