# Generated by Django 5.2.9 on 2026-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_schoolyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesomapping',
            name='academic_year',
            field=models.CharField(default='2023-2024', help_text='Academic year for this mapping', max_length=9),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
