# Generated by Django 5.2.9 on 2026-03-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_dedupe_coursesomapping_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['year'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
    ]
