# Generated by Django 5.2.5 on 2025-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Program Chair'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
