# Generated by Django 5.2.5 on 2026-04-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("import", "Import"),
                            ("save", "Save"),
                            ("security", "Security"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=100)),
                ("target_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
